CC = gcc

CFLAGS=-g

proj6: proj6.o frac_heap.o
	gcc $^ -o $@

test1: test1.o frac_heap.o
	gcc $^ -o $@

test2: test2.o frac_heap.o
	gcc $^ -o $@

test3: test3.o frac_heap.o
	gcc $^ -o $@

test4: test4.o frac_heap.o
	gcc $^ -o $@

test5: test5.o frac_heap.o
	gcc $^ -o $@

test6: test6.o frac_heap.o
	gcc $^ -o $@

clean:
	rm -f *.o *.out *.lst *~
